# Cấu hình Database H2 trên RAM (Tự động xóa và tạo lại bảng mỗi khi chạy)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:studentdb
quarkus.hibernate-orm.database.generation=drop-and-create

# Cho phép ứng dụng phục vụ file tĩnh và UI
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
