# Yêu cầu Hibernate tự động tạo bảng trong Database (H2/MySQL) nếu bảng chưa tồn tại
quarkus.hibernate-orm.database.generation=update

# Bật log SQL để dễ debug xem câu lệnh tạo bảng có chạy không
quarkus.hibernate-orm.log.sql=true